  
name: Build ESP-AT Project

on: push

jobs:

  build-esp32c3-mini-1-at:
    uses: ./.github/workflows/build_template_esp32c3.yml
    with:
      module_name: MINI-1
      artifacts_name: esp32c3-mini-1-at
    secrets: inherit
